### ISSUE TITLE
Problem about max part weight

### ISSUE THREAD

**Issue by zxxx200104** [kahypar/kahypar#111]
hello.
I noticed that the code supports setting target_block_weights. I would like to ask you if the code supports hard constraints (max_block_weights) for setting the maximum weights per block. Find the most suitable solution under the condition that the vertex weight of each block is not greater than the maximum weight. 
I tried to set the balance to be large enough so that the weight of each block does not exceed the maximum weight, and found that it can only find the optimal solution in a small range less than max_imbanlance, instead of finding the optimal solution in balance=0~max_imbanlance .

**Comment by SebastianSchlag** [comment]
Hi,
Thanks for reaching out. I am not sure I understand your issue. There are basically two ways the balance constraint can be addressed:
- In standard mode, KaHyPar will restrict the weight of the heaviest block to be at most (1+epsilon) times the average block weight. Hence, if your desired maximum block weight is `X`, you could compute an appropriate  imbalance factor epsilon such that `(1+epsilon) * c(V)/k <= X` (where `c(V)` is the sum of all vertex weights) and use that as input parameter.
- If you use `--use-individual-part-weights=true`, you can specify the maximum weight of each of  k blocks _individually_ via `--part-weights= B_1 B_2 B_3 ... B_k`, where `B_i` is the maximum weight that block `i` is allowed to have. Those constraints are hard in a sense that in this mode, KaHyPar does not consider the imbalance parameter epsilon at all.  As stated in the README, the sum of the individual maximum block weights `B_i` has to be a bit larger than the sum of all vertex weights of the hypergraph, since we currently don't support perfectly balanced partitioning.
