### ISSUE TITLE
Python Perform error

### ISSUE THREAD

**Issue by yun-lai-yun-qu** [kahypar/kahypar#122]
Hello,When I use this Python interface, it prompts the following error, I can't find the cause of the error and need your help:
do: kahypar.partition(hypergraph, context)
error: Invalid object identifier

**Comment by SebastianSchlag** [comment]
Hi @yun-lai-yun-qu, thanks for reaching out. We might need a bit more information in order to be able to figure out the root cause of this.
Could you please provide us with the python script that you use? Did you install the python interface from source or did you install the pypi package? What system/architecture are you on?

**Comment by javier-ruiz-lupon** [comment]
Hello, I had the same when running the code from [/Fanerst/simulate_sycamore](https://github.com/Fanerst/simulate_sycamore) (/bighead/order.py in line 86). I was using the pypi package in python 3.10.4. My solution to the problem was changing the Kahypar version to [1.1.6](https://pypi.org/project/kahypar/1.1.6/#files) instead of using the default 1.1.7 (I also changed version to python 3.7.4)

**Comment by SebastianSchlag** [comment]
Hey @javier-ruiz-lupon, thanks for letting us know. This is really odd. Could you provide us with detailed steps how to reproduce this problems with version 1.1.7?

**Comment by yun-lai-yun-qu** [comment]
> Hi @yun-lai-yun-qu, thanks for reaching out. We might need a bit more information in order to be able to figure out the root cause of this. Could you please provide us with the python script that you use? Did you install the python interface from source or did you install the pypi package? What system/architecture are you on?

**Comment by yun-lai-yun-qu** [comment]
Hello@SebastianSchlag,My Python version is 3.8, and I am running on Linux x86. I have tried both source installation and Pypi installation, but they both fail  when I execute Kahypar interface. The Python code I run is the following linked project: https://github.com/827916600/ClusterEnsembles/blob/main/tests/test_hbgf.py

**Comment by yun-lai-yun-qu** [comment]
@SebastianSchlag @javier-ruiz-lupon Yes,I also changed 1.1.7 to 1.1.6 and it worked, thank you very much

**Comment by yun-lai-yun-qu** [comment]
I also tried to install Python =3.7.4 and kahypar=1.1.6, and then ran the online Python example, but it gave me an error:Illegal instruction (core dumped)

**Comment by SebastianSchlag** [comment]
If I understand this correctly, your example code is using `solver='hbgf'` which seems to be using `pymetis`.  Looking at https://github.com/827916600/ClusterEnsembles/blob/8a82722b08c54a931050813a89e388e48b6c9cc9/ClusterEnsembles/ClusterEnsembles.py#L97, it seems that KaHyPar is only called for `solver='hgpa'`.

Could it be that this is actually a `pymetis` problem?

**Comment by SebastianSchlag** [comment]
Hi @yun-lai-yun-qu, just checking in. Have you seen my previous comment on this issue?

**Comment by SebastianSchlag** [comment]
Following up on this based on https://github.com/kahypar/kahypar/issues/130: The ` Invalid object identifier` error message indicates that the `ini` config file does not match the KaHyPar version used.
