### ISSUE TITLE
How do nodes with no hyperedges/nets associated with them get treated?

### ISSUE THREAD

**Issue by JMian** [kahypar/kahypar#128]
I noticed some hypergraphs from the benchmark set provided on http://algo2.iti.kit.edu/schlag/sea2017/ contain nodes that have no hyperedges/nets associated with them. For example, the hypergraph “Maragal_6.mtx.hgr” is to have 21251 hyperedges and 10152 nodes, according to the header(first line) of the .hgr file. When I looked into the file I could not find any hyperedge containing the nodes 2707, 3292, 3302, 3316, 7696, 8796, 8810, 9245. They are not written as being contained in a single-node net either because in contrast I can see for instance hyperedges in lines 10, 12, 14, 17, 18 etc. each is explicitly written down in a single line with a single node, indicating they are single-node net. 

When I run kahypar to partition this hypergraph into 8 blocks (k=8), in the top preprocessing step it said 68 hyperedges with |e|=1 were removed; this is the number of hyperedges that are explicitly written as single-node nets in the .hgr file. The 8 nodes mentioned above (2707, 3292, 3302, 3316, 7696, 8796, 8810, 9245) were all assigned to block 7 according to the output file. 

So how do the nodes with no hyperedges associated with them get treated during the process? Are they being considered during contraction and refinement and are their weight (unit weight) included in the calculation of the partition’s imbalance?

**Comment by SebastianSchlag** [comment]
Hi @JMian, thanks for reaching out.

 Since these nodes are isolated, they basically remain in the hypergraph during coarsening and don't become contracted. During initial partitioning, each one is then assigned to a block of the partition. This assignment depends on the initial partitioning algorithm. During refinement, those nodes might get moved because they effectively have a gain of zero, but a move could decrease the imbalance.

**Comment by JMian** [comment]
Thank you for the clarification !
