### ISSUE TITLE
More control about block weight

### ISSUE THREAD

**Issue by zypangpang** [kahypar/kahypar#129]
Hello, I am using kahypar to do some hypergraph partitioning and I noticed that if I set a fairly large imbalance parameter, e.g., 2, it is likely to get blocks with large weight 'gap'. For example, I might get 10 blocks with weights 100, 99, 98, **97, 60**, 59, **58, 10**, 5, 1, but I want the weights can decrease uniformly, for example,  100, 90, 80, 70, 60,50,40,30,20,10.  
In other words, I want the objective (cut net) to be minimized and at the same time, I don't need all block to be equally balanced. Their weights can be different but almost uniformly decreased. 
Is there any way to achieve this or similar behavior?

Thanks.

**Comment by SebastianSchlag** [comment]
Hi @zypangpang, thanks for reaching out. I am afraid this is not possible with KaHyPar or any other publicly available hypergraph partitioning system out of the box, because all of them target the balanced hypergraph partitioning problem in which the balancing constraint only enforces that no block is larger than 1 + ε times the average block weight.

However, you can use KaHyPar's [variable block weights feature](https://github.com/kahypar/kahypar#additional-features) and define a target weight upper bound for each individual block. This way, KaHyPar will try to partition the hypergraph such that those individual block weights are respected.

**Comment by zypangpang** [comment]
Thanks a lot. I will try it out.
