### ISSUE TITLE
Which config for my use case

### ISSUE THREAD

**Issue by erleria** [kahypar/kahypar#165]
Hi,

I would like to partition a graph which is a MxN grid.

I am just starting using kahypar. I use the C/C++ style library. I use the following config file _kahypar/config/km1_kKaHyPar_eco_sea20.ini_ (I just randomly selected one)

I want to partition the graph such that vertices that are close to each others are in the same partition. By **close** I mean on-grid distance (1 edge = 1 unit of distance).

However when I run the program (based on what I understand from the README) I get a partitioning that is not spatially coherent regarding the grid.
So I need to constrain the partitioning system but I don't know which functions/variables I need to paramterize. In my case all weights are the same (I do not prioritize the cut to occur somewhere)

I would like to know where to put my objective function or my constraints or my loss function and do I need to modify the config file so it matches my use case or is there an existing one that could fit ?

**Comment by kittobi1992** [comment]
Hi @erleria,

It is hard to guess why KaHyPar does not partition your grid into spatial coherent subregions without knowing more about your input and the exact partitioning call. In general, KaHyPar does not use geometric information when partitioning a graph and it can happen that a block of the partition contains several non-connected components. What you could try is to disable our community detection algorithm by setting `p-detect-communities=false` in the .ini file. It has been shown in the past that this component produces suboptimal solution for mesh-like networks. It would be further helpful if you share with us the dimension of your grid (NxM) and the exact partitioning call.

**Comment by SebastianSchlag** [comment]
Thanks for your reply @kittobi1992 . @erleria if you could share your graph in hMetis format that would help us as well to debug/reproduce this issue.

**Comment by N-Maas** [comment]
I would add that KaHyPar might not be the best fit for your use case, @erleria.

Since a grid graph has an extremely specific structure, you might get better results with simple geometric methods than with a general graph partitioning algorithm. Specifically, you could try to divide your grid graph into rectangles with (roughly) equal area. I think for grid graphs this is already close to the optimum in terms of edge cut.

**Comment by erleria** [comment]
Hi,

Thank you for your messages,

@kittobi1992 I checked, it was not that
@N-Maas Yes, that's right. However, let's say if I need 5 or 7 partitions on a 8x8 grid, then it's not straightforward how to divide automatically the grid, therefore partitioning algorithms for graphs seem to be a solution. 
Also I'm interested to know if there is a built-in function in KaHyPar to get the centroid (the vertex in/closest to the center) of a partition ?

I managed to get my program running as expected only with a 3x3 grid, I get some segfault for other sizes from the kahypar_partition function. 

`Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7da8f9b in kahypar::ds::GenericHypergraph<unsigned int, unsigned int, int, int, int, kahypar::meta::Empty, kahypar::meta::Empty>::GenericHypergraph(unsigned int, unsigned int, unsigned long const*, unsigned int const*, int, int const*, int const*) `

In my case I would like to work with 3x3 to (at most) 10x10 grids. When I try different small hacks to get the kahypar_partition working properly it still does not give a good partitioning (it does not necessarily mean that the hack is working either). Maybe my graph is ill formed, I have no clue.

@SebastianSchlag  I am not familiar with the hMetis format for graph but from the hMetis manual, page 12 they provide a format for unweighted hypergraphs, I think you are referring to this format. For a 3x3 grid, see below:

Graph
0 3
0 1
1 4
1 2
2 5
3 6
3 4
4 7
4 5
5 8
6 7
7 8

Partitions (vertex:partition), number of partitions = 2
0:0
1:1
2:1
3:0
4:0
5:1
6:0
7:0
8:1

Partitions in the grid (the type of output I'm expecting)
 0 1 1
 0 0 1
 0 0 1

I attach my code, it's almost a copy paste from the code in the readme.
[readmetest.cc.txt](https://github.com/kahypar/kahypar/files/11610909/readmetest.cc.txt)

**Comment by N-Maas** [comment]
Hi @erleria,

I tested your code and found that there are two errors with the generation of the input (i.e. `hyperedge_indices` and `hyperedges`). First, you create `hyperedge_indices` with `num_hyperedges` elements. However, you need an additional sentinel element at the last position (initialize with size `num_hyperedges + 1` and set last element to `2 * num_hyperedges`).

The second error is only relevant for non-quadratic grids, but you calculate the index on the grid incorrectly by using `grid_y` instead of `grid_x` for module and division.
Corrected:
```
      unsigned cur_x = vert_id%grid_x;
      unsigned cur_y = vert_id/grid_x;
```

KaHyPar currently doesn't validate the correctness of the input (you can instead build in Debug mode which should usually trigger an assertion in the case of invalid input, although the cause for the failing assertion might not always be obvious).

I'm quite sure both the segfaults and the weird partition output are caused by this.
With these fixes, I did a few test runs with grid sizes up to the order of 100x100 and k in {2, 7}. I got a very good result (equal sized rectangles ore very close to it) in all of those cases.

So if you need only small grids, KaHyPar should work very well.

(For sake of completeness: One approach for constructing a geometric algorithm for this problem would be to recursively divide the current sub-grid into two parts, i.e. a geometric version of our recursive bipartitioning.)

**Comment by N-Maas** [comment]
> Also I'm interested to know if there is a built-in function in KaHyPar to get the centroid (the vertex in/closest to the center) of a partition ?

No, there is nothing like that. KaHyPar only produces a partition, we don't provide functionalty for working with the result.

**Comment by erleria** [comment]
Hi @N-Maas ,

Thank you very much for pointing this out, this "sentinel" element was indeed missing. It seems to work pretty well.

I will look more into details this recursive bipartitioning, thank you for the suggestion.

I close this issue as the "weird" partitioning and segfault problems have been solved which were due to a missing element at the end of the hyperedge_indices array when I was creating my graph. Thanks for the help everyone.

**Comment by SebastianSchlag** [comment]
Thank you very much for looking into this @N-Maas! 👍
