### ISSUE TITLE
Combination of cut-net and connectivity metrics

### ISSUE THREAD

**Issue by rchen234** [kahypar/kahypar#171]
Hi all,

We are considering a matrix partitioning problem which involves minimizing a combination of the cut-net and connectivity metrics. Specifically, we have two different types of hyperedges, say E1 and E2. We want to minimize a particular combination of the cut-net of hyperedges in E1 and connectivity of hyperedges in E2, i.e., $\alpha$ cut-net(E1)+(1- $\alpha$)connectivity(E2). The hyperedge weights are identical.

I wonder if the current KaHyPar can deal with such an objective. If not, do you think it is hard to modify the code for our purpose ourselves?

Thanks,
Rui

**Comment by kittobi1992** [comment]
Hello @rchen234,

In general, it is not an easy task to add a new objective function to KaHyPar since gain computations (improvement in the objective function) are tightly coupled with our refinement algorithms and need deep knowledge of the underlying code when you want to change that. However, there exists a shared-memory parallelization of KaHyPar called Mt-KaHyPar:
https://github.com/kahypar/mt-kahypar
The highest-quality configuration of Mt-KaHyPar achieves the same solution quality than KaHyPar while being an order of magnitude faster with only ten threads. I have recently put a lot of efforts into a change that separates the gain computation logic from our local search algorithms, which allows to add new objective functions to our partitioner without touching the local search algorithms. But it is still not an easy task and requires at least a high-level understanding of how our algorithms work. I have also written a step-by-step guide how new objective functions can be added to Mt-KaHyPar:
https://github.com/kahypar/mt-kahypar/tree/master/mt-kahypar/partition/refinement/gains
My first guess is that it should be not that hard to implement your specific objective function. If you decide to implement it in Mt-KaHyPar, I am happy to assist you if you have any questions.

Best,
Tobias

**Comment by SebastianSchlag** [comment]
I'd second what @kittobi1992 wrote above. Given that Mt-KaHyPar already supports both `cut` and `connectivity` metrics, implementing a metric that takes both into account might not be that difficult.

**Comment by rchen234** [comment]
Hi @kittobi1992 @SebastianSchlag ,

Thank you for your replies. We will look into Mt_KaHyPar and let you know if we need any help.

Best,
Rui

**Comment by SebastianSchlag** [comment]
@rchen234 I'll close this issue. If you need any help with Mt-KaHyPar, please feel free to open up another issue there.
