### ISSUE TITLE
lower bound 

### ISSUE THREAD

**Issue by onefanwu** [kahypar/kahypar#182]
Hi KaHyPar team, I would like to know if there is some lower bound about the solution quality of the balanced k-way hypergraph partitioning problem. Is there some public information on KaHyPar's worst-case ratio for solution quality?

**Comment by larsgottesbueren** [comment]
Hi Yifan,

We can't prove any theoretical approximation ratios for two reasons. Our algorithms are purely heuristics, they can get stuck in some poor local optima. More importantly though, because the partitioning problem itself does not permit constant-factor approximations; see for example the following reference https://www.sciencedirect.com/science/article/abs/pii/002001909290140Q.

There are some algorithms with not very nice and super-constant approximation guarantees (such as O(log^2(n) / e^4) and similar). I know of one implementation, which is quite slow (it takes > 2 minutes on a 600 node graph).

There have been some studies where an optimal solution was found on small graphs, and heuristics similar to ours found optimal or near-optimal solutions, but this doesn't say anything about worst-case guarantees.

I hope this information is helpful, and let me know if you have further questions.
Best,
Lars

**Comment by onefanwu** [comment]
Hi Lars,
Thank you so much for your helpful replies, they have solved my problem.
