### ISSUE TITLE
HELP - How big graph does the KaHyPar support ?

### ISSUE THREAD

**Issue by zbj2008cn** [kahypar/kahypar#213]
Hello, I m trying to use KaHyPar to do some hypergraph partition works. 

I have a hypergraph with 90,000,000 nodes and 95,000,000 edges and want to partition it into 100,000 parts. 

So Can it be supported by KaHyPar? If it can, is there some recommended setting for this kind huge graph? Thanks!

**Comment by N-Maas** [comment]
Hi @zbj2008cn,

the size of the hypergraph is actually not the main problem, though KaHyPar would indeed need a while for hypergraphs of this size (how large are the hyperedges, btw?). However, 100,000 parts is much too large for the standard configuration of KaHyPar. It might be possible when using recursive bisection (rKaHyPar config) since it shouldn't use as much memory, but I'm not sure how it behaves for values that large.

Anyways, the much better option is using [Mt-KaHyPar](https://github.com/kahypar/mt-kahypar/) instead, which provides a large k configuration for exactly this use case. More details are in the readme of Mt-KaHyPar.

**Comment by zbj2008cn** [comment]
Thanks @N-Maas ,

the input information :

Type: edgeWeights=false nodeWeigths=false
# HNs : 84462159 # HEs : 94170733 # pins : 338914355

nblocks is set to 2(version1) or 131072(version2). They have being still stuck there.

I m trying to partition it by Mt-KaHyPar. Thanks！

**Comment by zbj2008cn** [comment]
New Update, my massive hyper graph run out result of nblock=2 option and total run time is 69488.2s.

Partition Result : 

Hpyeredge Cut (minimize) =4472
SOED (mini) =8944
(k-1) (mini) =4472
Absorption (max) =9.41683e+07
Imblance =0.0490594

Partition sizes and weights:
Part 0 = 44302913 w( 0 ) = 44302913
Part 1 = 40159246 w( 1 ) = 40159246

Timings:
Partition time = 69488.2 s
    + Input Validation = 4.93607s
    +Preprocessing =8537.28s
           min hash sparsifier = 0s
           community detection = 8537.28s
    +Coarsening =1072.67s
    +Initial Partitioning = 4.80695s
    +Local Search =59790.7s
