### ISSUE TITLE
Confusion for function LabelPropagationInitialPartitoner::computeMaxGainMoveForUnssignedSourcePart(const HypernodeID hn)

### ISSUE THREAD

**Issue by Frandy** [kahypar/kahypar#34]
Hi, 
I'm studying hypergraph partition for vlsi circuit and found this library. It is great and I can learn a lot.
While I got confused when reading the function LabelPropagationInitialPartitoner::computeMaxGainMoveForUnssignedSourcePart(const HypernodeID hn).
When he connectivity > 1, then tmp_scores for all connected part is 0. how does it can get the part with max_score ?

I have read the contributing guidelines, and not sign it yet. I think I will sign it if I deliver code.

Best wishes,
Frandy

**Comment by kittobi1992** [comment]
Hi Frandy,
thanks for choosing KaHyPar as the source for learning more about hypergraph partitioning.

To your question: First you should have look how max_score is initialized:
Gain max_score = std::numeric_limits<Gain>::min(); => max_score = -2147483647.
Furthermore, we iterate over all hyperedges of a hypernode. Some hyperedges will have connectivity equal to 1 and some > 1. Meaning, you can never say what the exact values of tmp_scores are.

But before going more in detail you should have a look at the assertion in line 247 - 262. The assertions verifies that the calculated gain in tmp_scores to a part 'target_part' is equal with the FM gain for moving it to that part. The algorithm here is splitted in two stages.
First we iterate over all incident edges of the hypernode (which we want to assign to a part). We only want to assign it to a part, where it is currently incident via a hyperedge. Therefore, we use the bitset valid_parts. If a hypernode is in a hyperedge with connectivity equal to 1, we would make the hyperedge cut, if we would not assign it to that part. By summing up the hyperedge weights in internal_weight and in the respective connected part in tmp_scores, one can show that the FM gain for each part is equal to tmp_scores[ part ] - internal_weight.

Note, the FM gain for an unassigned hypernode can never be positive, because it can only increase the connectivity of a hyperedge (but never decrease).

Best,
Tobias

**Comment by kittobi1992** [comment]
Hi Frandy,

on a high level you can look at the algorithm, that it will select the part with the highest FM gain, when moving the hypernode to the corresponding part. Back to your question: You are right, it will choose the one with largest weight among all edges with connectivity = 1. We substract the internal_weight such that we can assert that we have calculated the correct FM gain.

Best,
Tobias
