### ISSUE TITLE
Precompiled python interface issues on Mac

### ISSUE THREAD

**Issue by filipmazurek** [kahypar/kahypar#63]
System specifications: 
MacOS 10.15.5

I installed the precompiled Python interface of KaHyPar using `python3 -m pip install --index-url https://pypi.org/simple/ --no-deps kahypar`. 

I created a file which has the python example code - when I run the file using the Terminal, I receive an error `Could not load context file at: <path/to/config>/km1_kKaHyPar_dissertation.ini`

I was having the same issues as in Issue #58 when I built KaHyPar on my machine, so I decided to try the precompiled version instead, but it seems there is some other problem with it.

**Comment by SebastianSchlag** [comment]
Hi Filip, 
thanks for reaching out. It seems like you did not specify the path to the configuration properly. In the example, you have to change `<path/to/config>/km1_kKaHyPar_dissertation.ini` to match the path on you system. If you cloned the kahypar repository to your home direction, for example, you'll have to change it to `/Users/<your-username>/kahypar/config/km1_kKaHyPar_sea20.ini`.

Also, it seems like the example is outdated, since the `km1_kKaHyPar_dissertation.ini` config now resides in `/config/old_reference_configs/km1_kKaHyPar_dissertation.ini`.

I'll update the example accordingly.

**Comment by filipmazurek** [comment]
Hi Sebastian,
I can't believe I missed that - thanks for pointing me in the right direction. Looks like the old configs have some illegal options in them (such as `r-type=kway_fm_flow_km1`), but the newer configs work well. I appreciate the help!

**Comment by SebastianSchlag** [comment]
Hehe, no problem! 

Yes, the old config rely on an older version of KaHyPar, which is why I moved them to the `old_reference_configs` folder.   More information on that can be found here: with https://github.com/kahypar/kahypar#old-presets

**Comment by yinyee** [comment]
Hi @SebastianSchlag sorry for the dense question, but I cannot locate the configuration file `km1_kKaHyPar_sea20.ini`.  I installed KaHyPar via 'pip install kahypar' command in my Dockerfile.  For additional context, I'm using Windows Subsystem for Linux.

`pip show kahypar` returns
```
Name: kahypar
Version: 1.3.2
Summary: Python Inferface for the Karlsruhe Hypergraph Partitioning Framework (KaHyPar)
Home-page: https://www.kahypar.org
Author: Sebastian Schlag
Author-email: kahypar@sebastianschlag.de
License:
Location: /opt/conda/lib/python3.10/site-packages
Requires:
Required-by:
```
I've looked in:
-  `/opt/conda/lib/python3.10/site-packages/`
- `/usr/local/lib/python3.10/dist-packages/`

**Comment by SebastianSchlag** [comment]
Hey @yinyee, no worries. I'm glad that you found them. 🙂
