### ISSUE TITLE
Scalability? 

### ISSUE THREAD

**Issue by remysucre** [kahypar/kahypar#68]
How how large of a graph can KaHyPar scale to? It would be nice to have some simple numbers on the running time for large graphs on the website. I can't tell much from the current plots.

**Comment by SebastianSchlag** [comment]
@larsgottesbueren, could you provide some numbers for the latest KaHyPar-HFC version? Maybe just a simple .csv file with `Hypergraph, |V|, |E|, |P|, median degree, average degree, median net size average net size, k, epsilon, running time` as columns?

**Comment by remysucre** [comment]
Table 1 of [this paper](https://arxiv.org/pdf/2003.12110v1.pdf) is helpful, but I'm having a hard time connecting it to the running time measurements.

**Comment by larsgottesbueren** [comment]
Hi, 

I've compiled a small csv file with numbers for a sample of 'large' hypergraphs and k = 8,32,128, direct k-way mode, km1 objective, from the latest run on the 2019 Cascade Lake machines. (.txt because github accepts only certain file endings)
[example_stats.csv.txt](https://github.com/kahypar/kahypar/files/5101564/example_stats.csv.txt)
Let me know, if you need more numbers.

Generally, you should be fine with anything up to 20 million pins and k <= 128, but running time is influenced by a lot of different factors. With HFC refinement, KaHyPar can even be faster for larger k.

If running time becomes an issue for you, there's a new feature where you can set a time limit, after which we don't perform any more refinement and only finish projecting up the partition (obviously only works once KaHyPar is in the refinement stage).
If you're working on REALLY large instances, please send either of us an email.

**Comment by larsgottesbueren** [comment]
There's unfortunately no one-click solution for this. The csv is generated from two different sources -- experimental data from running the partitioner and a stats tool (see tools/hypergraph_statistics.cc I believe), though I just took a preexisting stats file.
To get started, the following command will give you one of the runs for the first line in the csv.

    ./kahypar/application/KaHyPar -h ~/path-to-hypergraphs/wb-edu.mtx.hgr -k 8 -e 0.03 -o km1 -m direct -p ../config/km1_kKaHyPar_sea20.ini

We provide presets, e.g. config/km1_kKaHyPar_sea20.ini for optimizing km1, which you can set with the -p argument.
We recommend using the direct k-way version (kKaHyPar in the preset files).
You can choose between two objective functions km1 or cut, whichever is better suited for your application.
The parameters -m(ode) and -o(bjective) always have to be set.
The --help argument displays a description for every parameter.

**Comment by remysucre** [comment]
Perfect, thanks! I'm closing this issue for now. Feel free to reopen if you are putting this onto the website and need to keep track.

**Comment by SebastianSchlag** [comment]
Thank you @larsgottesbueren !
