### ISSUE TITLE
imbalance and part-weights are not being honored

### ISSUE THREAD

**Issue by chiragrs88** [kahypar/kahypar#84]
I have a graph with 26 vertices with weight 1 and 71 vertices with weight 0 and need to partition into 2 blocks with weights 29 25 (--part-weights 29 25).

I get a final solution like this:
Partition sizes and weights:  
|part 0 | =  1  w( 0 ) =  0 
|part 1 | = 96  w( 1 ) = 26 

where part 1 is overutilized.

Also, regardless of imbalance/epsilon value, result is the same and the initial report says epsilon = 0.

Attached are the hypergraph and fix files, as well as the ini file

Command used:
KaHyPar -p cut.ini --mode direct --blocks 2 --objective cut --write-partition true -h tmp1.hgr -f tmp1.fix --use-individual-part-weights=true --part-weights 29 25 -e 0.5

[cut.ini.txt](https://github.com/kahypar/kahypar/files/6557859/cut.ini.txt)
[tmp1.hgr.txt](https://github.com/kahypar/kahypar/files/6557853/tmp1.hgr.txt)
[tmp1.fix.txt](https://github.com/kahypar/kahypar/files/6557854/tmp1.fix.txt)

**Comment by SebastianSchlag** [comment]
Hi @chiragrs88,

thanks for reaching out.

Vertices with a weight of `0` are currently not supported as KaHyPar assumes each vertex to have a weight of at least `1`.
I think that might be the reason for the results you are seeing.  

When adjusting the vertex weights and individual part weights, the results look reasonable. However, you might run into an error message like

> WARNING: Fixed vertex subgraph is imbalanced. Switching to direct k-way initial partitioning!
> [bin_packing_utils.h:setPart:46]: Assertion `bin >= 0 && index < _parts.size()` failed: Invalid bin id:  bin = 1

This is, because we got new weight-balancing algorithms in place and the code to handle individual part weights has not been merged to master yet. However, the PR for this feature is already out: https://github.com/kahypar/kahypar/pull/82 
Hopefully, we'll be able to merge it soon.

In the meantime, please feel free to checkout branch `N-Maas:bp_individual_part_weights` to use individual block weights.

I'll also follow up and add a warning / error message to KaHyPar's output in case a hypergraph contains zero-weighted vertices.

**Comment by SebastianSchlag** [comment]
Also bringing in @kittobi1992, who implemented the fixed-vertex support.

**Comment by N-Maas** [comment]
So the error mentioned by Sebastian happens because of a weird interaction between fixed vertices and the newly added bin packing initial partitioner. Unfortunately, therefore it also doesn't work on my branch yet. But we will fix it soon (within PR #82).
