### ISSUE TITLE
manual for kahypar and benchmarks

### ISSUE THREAD

**Issue by peyaj** [kahypar/kahypar#91]
Just as metis and hmetis have their user manuals which describe the different options that are available, can you also provide a manual for kahypar? This will enable new users to quickly start using your excellent system. Also, is there a set of  large-ish benchmarks (and their kahypar outputs) available for comparison?

**Comment by SebastianSchlag** [comment]
Hi @peyaj, thanks for reaching out.

Having a decent manual is one thing that we already have on our todo list for quite a while. To be honest, I guess it likely won't happen soon, as everyone involved in the project is extremely busy.

In general, for normal end users, the project readme should suffice to get started and it should be enough to use one of our predefined configs that were specifically tuned to create high-quality solutions.

If you are more interested in what's going on under the hood, `./KaHyPar --help` offers a brief description of all the parameters. Since we don't have more documentation available at the moment, please feel free to reach out to me, @kittobi1992, or @larsgottesbueren (or write an email to our mailing list) if you have more questions.

Regarding benchmarks: We've got several results on large benchmark sets (involving hypergraphs from VLSI design, SAT solving, and sparse matrix computations) available at https://github.com/kahypar/kahypar#additional-resources. I think the ones for the SEA'20 paper are already online but not publicly accessible yet. @larsgottesbueren could you make them publicly available?

**Comment by larsgottesbueren** [comment]
The results for SEA 20 are available here https://github.com/kahypar/experimental-results/tree/master/sea20 and are now linked in the front-page readme
